![Práctica 4 - Librería PANDAS](img/cabecera-Pandas.png)

### REALIZADA POR: Adrián Benítez Roldán y Alejandro Montes Cantero

# Pandas.

## Introducción

Pandas es una librería muy poderosa para la manipulación y el análisis de datos. Se puede considerar como una versión de Excel con muchas más características. A continuación se verán los siguientes apartados:

* Series.
* DataFrames.
* Datos no válidos.
* GroupBy.
* Mezcla, unión y concatenación.
* Operaciones.
* Entrada y salida de datos.

---
## Series

Las *Series* son el tipo de dato principal en Pandas. Una Serie es muy parecida a un array de Numpy. Sin embargo, una Serie puede tener etiquetas para cada eje, de forma que puede accederse por el nombre de etiqueta en lugar de por posición. Además pueden almacenar cualquier tipo de dato u objeto de Python, incluso dentro del mismo objeto Serie.

Para comenzar importamos la librería Pandas (junto con Numpy para realizar varios ejemplos).

In [2]:
import numpy as np
import pandas as pd

### Creando Series

Se puede crear una Serie a partir de una lista, un array de Numpy o un diccionario. Para ello utilizamos el constructor *Series*. A continuación vamos a ver algunos ejemplos:

In [297]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

**A partir de listas**

Indicando como parámetro *data* la lista que vamos a transformar.

In [298]:
pd.Series(data=d)

a    10
b    20
c    30
dtype: int64

In [299]:
pd.Series?

Init signature:
pd.Series(
    data=None,
    index=None,
    dtype: 'Dtype | None' = None,
    name=None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
One-dimensional ndarray with axis labels (including time series).

Labels need not be unique but must be a hashable type. The object
supports both integer- and label-based indexing and provides a host of
methods for performing operations involving the index. Statistical
methods from ndarray have been overridden to automatically exclude
missing data (currently represented as NaN).

Operations between Series (+, -, /, \*, \*\*) align values based on their
associated index values-- they need not be the same length. The result
index will be the sorted union of the two indexes.

Parameters
----------
data : array-like, Iterable, dict, or scalar value
    Contains data stored in Series. If data is a dict, argument order is
    maintained. Unordered sets are not supported.
index : array-like or Index (1d)
    Values must be hashable and have the same length as `data`.
    Non-unique index values are allowed. Will default to
    RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
    and index is None, then the keys in the data are used as the index. If the
    index is not None, the resulting Series is reindexed with the index values.
dtype : str, numpy.dtype, or ExtensionDtype, optional
    Data type for the output Series. If not specified, this will be
    inferred from `data`.
    See the :ref:`user guide <basics.dtypes>` for more usages.
name : Hashable, default None
    The name to give to the Series.
copy : bool, default None
    Whether to copy input data, only relevant for array, Series, and Index
    inputs (for other input, e.g. a list, a new array is created anyway).
    Defaults to True for array input and False for Index/Series.
    Even when False for Index/Series, a shallow copy of the data is made.
    Set to False to avoid copying array input at your own risk (if you
    know the input data won't be modified elsewhere).
    Set to True to force copying Series/Index input up front.

See Also
--------
DataFrame : Two-dimensional, size-mutable, potentially heterogeneous tabular data.
Index : Immutable sequence used for indexing and alignment.

Notes
-----
Please reference the :ref:`User Guide <basics.series>` for more information.

Examples
--------
Constructing Series from a dictionary with an Index specified

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["a", "b", "c"])
>>> ser
a   1
b   2
c   3
dtype: int64

The keys of the dictionary match with the Index values, hence the Index
values have no effect.

>>> d = {"a": 1, "b": 2, "c": 3}
>>> ser = pd.Series(data=d, index=["x", "y", "z"])
>>> ser
x   NaN
y   NaN
z   NaN
dtype: float64

Note that the Index is first built with the keys from the dictionary.
After this the Series is reindexed with the given Index values, hence we
get all NaN as a result.

Constructing Series from a list with `copy=False`.

>>> r = [1, 2]
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
[1, 2]
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `copy` of
the original data even though `copy=False`, so
the data is unchanged.

Constructing Series from a 1d ndarray with `copy=False`.

>>> r = np.array([1, 2])
>>> ser = pd.Series(r, copy=False)
>>> ser.iloc[0] = 999
>>> r
array([999,   2])
>>> ser
0    999
1      2
dtype: int64

Due to input data type the Series has a `view` on
the original data, so
the data is changed as well.
File:           c:\users\benro\appdata\local\programs\python\python313\lib\site-packages\pandas\__init__.py
Type:           type
Subclasses:     SubclassedSeries

Tambien se puede pasar una lista de etiquetas para cada fila:

In [300]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [301]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

También se pueden indicar la lista y las etiquetas de fila como primer y segundo parámetro (sin indicar el nombre):

In [302]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

**A partir de arrays de NumPy**

In [303]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [304]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

**A partir de un Diccionario**

In [305]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Tipos de datos de un objeto Series

Un objeto Series de Pandas puede almacenar cualquier tipo de dato u objeto. Desde cadenas de texto:

In [306]:
pd.Series(data=['uno','dos','tres'])

0     uno
1     dos
2    tres
dtype: str

Definiciones de funciones:

In [307]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [308]:
funciones=pd.Series([sum,print,len])
funciones[1]('hola mundo')

hola mundo

Hasta objetos de distintos tipos:

In [309]:
pd.Series([1.7,'no valido',9,3j])

0          1.7
1    no valido
2            9
3           3j
dtype: object

## Utilizando índices

La clave para utilizar un objeto Series está en comprender sus índices. Pandas puede utilizar como índices nombres o números para acceder a sus datos. Trabaja de la misma manera que una tabla hash o un diccionario.

Veamos algunos ejemplos:

In [310]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                                   

ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [311]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [312]:
ser1['USA']

np.int64(1)

Cualquier operación que se realice estará basada en los índices de las Series:

In [313]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

---
## DataFrames

Los DataFrames de Pandas son las estructuras mas utilizadas y están inspiradas en el lenguaje de programación R. Un DataFrame es como un grupo de objetos de tipo Series que comparten un mismo índice, y en el que cada serie puede tener un nombre. En resumen, es una estructura de dos dimensiones donde cada fila y cada columna puede tener una etiqueta.

In [314]:
df = pd.DataFrame(np.random.randn(5,4), index='A B C D E'.split(), columns='W X Y Z'.split())
df

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

### Selección e índices.

Veamos varias maneras de manipular un DataFrame. En primer lugar podemos acceder a toda una columna indicando el nombre de dicha columna:

In [315]:
df['W']

A   -0.358180
B   -1.859282
C   -0.205111
D    1.862929
E    1.891898
Name: W, dtype: float64

In [316]:
df['W']

A   -0.358180
B   -1.859282
C   -0.205111
D    1.862929
E    1.891898
Name: W, dtype: float64

In [317]:
df['W']['A']

np.float64(-0.35818020020146063)

Si queremos obtener los datos de varias columnas, hay que utilizar una lista con el nombre de las columnas:

In [318]:
df[['W','Z']]

          W         Z
A -0.358180 -0.300503
B -1.859282  1.871184
C -0.205111 -0.875939
D  1.862929  0.017774
E  1.891898  0.767851

Cuando obtenemos un columna lo que nos devuelve es un objeto de tipo Series:

In [319]:
type(df['W'])

pandas.Series

**Creando un nueva columna:**

In [320]:
df['new'] = df['W'] + df['Y']#crea una nueva columna

df

          W         X         Y         Z       new
A -0.358180  1.122178  0.710526 -0.300503  0.352346
B -1.859282  1.144544 -1.204954  1.871184 -3.064236
C -0.205111  0.726358 -0.889578 -0.875939 -1.094689
D  1.862929 -1.750663  0.023790  0.017774  1.886719
E  1.891898 -0.655604 -0.334257  0.767851  1.557641

**Eliminando columnas**: Con el método *drop* podemos obtener un DataFrame sin la columna indicada.

In [321]:
df.drop('new',axis=1)# en realidad crea una copia, el dataframe sigue siendo el mismo

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

Sin embargo, el funcionamiento por defecto del método no elimina la columna del DataFrame.

In [322]:
df

          W         X         Y         Z       new
A -0.358180  1.122178  0.710526 -0.300503  0.352346
B -1.859282  1.144544 -1.204954  1.871184 -3.064236
C -0.205111  0.726358 -0.889578 -0.875939 -1.094689
D  1.862929 -1.750663  0.023790  0.017774  1.886719
E  1.891898 -0.655604 -0.334257  0.767851  1.557641

Para que elimine la columna del DataFrame hay que indicarselo de forma explícita con el parámetro *inplace*:

In [323]:
df.drop('new',axis=1,inplace=True) #el parámetro inplace suelen tenerlo todos los métodos,
#permite no crear copias sino usar el mismo dataframe

df

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

También se pueden eliminar filas con este método:

In [324]:
df.drop('E',axis=0)

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774

**Seleccionando filas**.

El método `loc` nos permite obtener los datos de una fila:
(los devuelve como una Serie)

In [325]:
df.loc['A']

W   -0.358180
X    1.122178
Y    0.710526
Z   -0.300503
Name: A, dtype: float64

Podemos seleccionar una fila por su posición en lugar de su etiqueta utilizando el método `iloc`:

In [326]:
df.iloc[2]

W   -0.205111
X    0.726358
Y   -0.889578
Z   -0.875939
Name: C, dtype: float64

**Seleccionando subconjuntos de filas y columnas**

Se pasa fila y columna:

In [327]:
df.loc['B','Y']

np.float64(-1.2049538183665263)

Si se pasa lista de filas y lista de columnas:

In [328]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -0.358180  0.710526
B -1.859282 -1.204954

In [329]:
df

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

### Selección condicional

Una característica importante de Pandas es la selección condicional, muy parecida a la utilizada en Numpy.

In [330]:
df

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

Si comparamos un DataFrame completo con un valor obtendremos un nuevo DataFrame con valores lógicos (True/False) indicando que valores del DataFrame cumple la condición.

In [331]:
df>0

       W      X      Y      Z
A  False   True   True  False
B  False   True  False   True
C  False   True  False  False
D   True  False   True   True
E   True  False  False   True

Este DataFrame de lógicos se puede utilizar para seleccionar aquellos valores que tienen su valor a verdadero (`True`):

In [332]:
df[df>0]

          W         X         Y         Z
A       NaN  1.122178  0.710526       NaN
B       NaN  1.144544       NaN  1.871184
C       NaN  0.726358       NaN       NaN
D  1.862929       NaN  0.023790  0.017774
E  1.891898       NaN       NaN  0.767851

In [333]:
df[df>0]
nuevo=df.fillna(75)
nuevo

          W         X         Y         Z
A -0.358180  1.122178  0.710526 -0.300503
B -1.859282  1.144544 -1.204954  1.871184
C -0.205111  0.726358 -0.889578 -0.875939
D  1.862929 -1.750663  0.023790  0.017774
E  1.891898 -0.655604 -0.334257  0.767851

In [334]:
df[df>0]=100
df

            W           X           Y           Z
A   -0.358180  100.000000  100.000000   -0.300503
B   -1.859282  100.000000   -1.204954  100.000000
C   -0.205111  100.000000   -0.889578   -0.875939
D  100.000000   -1.750663  100.000000  100.000000
E  100.000000   -0.655604   -0.334257  100.000000

In [335]:
df[df['W']>0]
df

            W           X           Y           Z
A   -0.358180  100.000000  100.000000   -0.300503
B   -1.859282  100.000000   -1.204954  100.000000
C   -0.205111  100.000000   -0.889578   -0.875939
D  100.000000   -1.750663  100.000000  100.000000
E  100.000000   -0.655604   -0.334257  100.000000

Si utilizamos esta característica para una sóla columna, podemos filtrar el DataFrame para obtener sólo las filas cuya columna cumpla la condición dada:

In [336]:
df[df['W']>0]

       W         X           Y      Z
D  100.0 -1.750663  100.000000  100.0
E  100.0 -0.655604   -0.334257  100.0

In [337]:
df[df['W']>0]['Y']

D    100.000000
E     -0.334257
Name: Y, dtype: float64

In [338]:
df[df['W']>0][['Y','X']]

            Y         X
D  100.000000 -1.750663
E   -0.334257 -0.655604

Se pueden aplicar varias condiciones utilizando los operadores lógicos *O* (`|`) e *Y* (`&`) con paréntesis:

In [339]:
df[(df['W']>0) & (df['Y'] < -1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

### Mas detalles sobre los índices

Sobre los índices se pueden realizar distintos tipos de operaciones, como por ejemplo: reiniciarlos, cambiarlos por otros nuevos o crear una jerarquía de índices. Los índices son como otro tipo de datos

In [340]:
df = pd.DataFrame(np.random.randn(5,4), index='A B C D E'.split(), columns='W X Y Z'.split())
df

          W         X         Y         Z
A -1.660475 -1.993484  0.862909 -0.674535
B -0.385961 -0.701167 -0.406243 -1.328714
C -0.384433  0.571082  0.117548  0.670416
D -1.270170  0.074613 -0.242051 -0.592879
E  0.287735  0.340519 -0.473382  0.129210

**Resetear índices**: Utilizamos el método `reset_index` para inicializar los índices a sus valores numéricos por defecto (empezando por 0). Esto nos creará una nueva columna llamada `index` con los índices antíguos:

In [341]:
df.reset_index()

  index         W         X         Y         Z
0     A -1.660475 -1.993484  0.862909 -0.674535
1     B -0.385961 -0.701167 -0.406243 -1.328714
2     C -0.384433  0.571082  0.117548  0.670416
3     D -1.270170  0.074613 -0.242051 -0.592879
4     E  0.287735  0.340519 -0.473382  0.129210

Pero no modifica el objeto, en realidad lo que hace es una copia.

In [342]:
df

          W         X         Y         Z
A -1.660475 -1.993484  0.862909 -0.674535
B -0.385961 -0.701167 -0.406243 -1.328714
C -0.384433  0.571082  0.117548  0.670416
D -1.270170  0.074613 -0.242051 -0.592879
E  0.287735  0.340519 -0.473382  0.129210

**Nuevos índices**: Para crear nuevos índices, primero tenemos que crear una nueva columna con los nombres de los índices y posteriormente indicamos que esta nueva columna se utilizará como índices:

In [343]:
newind = 'CA NY WY OR CO'.split()

df['States'] = newind

df

          W         X         Y         Z States
A -1.660475 -1.993484  0.862909 -0.674535     CA
B -0.385961 -0.701167 -0.406243 -1.328714     NY
C -0.384433  0.571082  0.117548  0.670416     WY
D -1.270170  0.074613 -0.242051 -0.592879     OR
E  0.287735  0.340519 -0.473382  0.129210     CO

In [344]:
df.set_index('States')

               W         X         Y         Z
States
CA     -1.660475 -1.993484  0.862909 -0.674535
NY     -0.385961 -0.701167 -0.406243 -1.328714
WY     -0.384433  0.571082  0.117548  0.670416
OR     -1.270170  0.074613 -0.242051 -0.592879
CO      0.287735  0.340519 -0.473382  0.129210

Todas estas operaciones no se realizarán de forma permanente en el DataFrame a menos que se le indíque implícitamente con el parámetro `inplace`.

In [345]:
df

          W         X         Y         Z States
A -1.660475 -1.993484  0.862909 -0.674535     CA
B -0.385961 -0.701167 -0.406243 -1.328714     NY
C -0.384433  0.571082  0.117548  0.670416     WY
D -1.270170  0.074613 -0.242051 -0.592879     OR
E  0.287735  0.340519 -0.473382  0.129210     CO

In [346]:
df.set_index('States',inplace=True)

df

               W         X         Y         Z
States
CA     -1.660475 -1.993484  0.862909 -0.674535
NY     -0.385961 -0.701167 -0.406243 -1.328714
WY     -0.384433  0.571082  0.117548  0.670416
OR     -1.270170  0.074613 -0.242051 -0.592879
CO      0.287735  0.340519 -0.473382  0.129210

### Multi-índices y jerarquía de índices.

Un DataFrame puede tener varias columnas índices.

A continuación vamos a ver como trabajar con multi-índices. Primero vamos a crear un pequeño ejemplo de un DataFrame que tiene varios índices (e incluso jerárquicos):

In [347]:
# Creamos los multi-índices
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
tuples = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(tuples)

hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [348]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1 -0.194820  2.038608
   2  1.822763  1.890796
   3  0.750161 -0.020539
G2 1 -0.141380  0.238518
   2 -0.677293  0.763918
   3 -0.124788  0.422400

Veamos algunos ejemplo de como funcionan estos índices. Podemos acceder al primer índice utilizando el método `loc` y obtendremos un *sub-dataframe*:

In [349]:
df.loc['G1']

          A         B
1 -0.194820  2.038608
2  1.822763  1.890796
3  0.750161 -0.020539

In [350]:
df.loc['G1'].loc[1]

A   -0.194820
B    2.038608
Name: 1, dtype: float64

Los índices utilizados no tienen nombre propio, pero se les puede asignar un nombre a cada uno para diferenciarlos.

In [351]:
df.index.names

FrozenList([None, None])

In [352]:
df.index.names = ['Group','Num']

df

                  A         B
Group Num
G1    1   -0.194820  2.038608
      2    1.822763  1.890796
      3    0.750161 -0.020539
G2    1   -0.141380  0.238518
      2   -0.677293  0.763918
      3   -0.124788  0.422400

Con el método `xs` se pueden obtener los datos de los índices que queramos:

In [353]:
df.xs('G1')

            A         B
Num
1   -0.194820  2.038608
2    1.822763  1.890796
3    0.750161 -0.020539

In [354]:
df.xs(['G1',1])

TypeError: list keys are not supported in xs, pass a tuple instead

In [ ]:
df.xs(1,level='Num')

---
## Datos no válidos.

Cuando filtramos los datos de un DataFrame, los datos que no cumplen la condición se representan como `NaN`(*Not a Number*). Estos datos no datos también se conocen como *datos perdidos*.

Veamos algunos métodos que nos permiten trabajar con este tipo de datos en Pandas.

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

**dropna**: Permite recuperar aquellos datos válidos del DataFrame. Quita filas que tenga algún valor NaN. No modifica dataset original

In [ ]:
df.dropna()

In [ ]:
df.dropna(axis=1) # Elimina columnas que tenga algún valor NaN

Con el parámetro `thresh` se puede indicar a partir de que cantidad de datos no válidos no se recuperan.

In [ ]:
df.dropna(thresh=2)

**fillna**: Se utiliza para indicar el valor por defecto por el que se sustituirá los datos no válidos.

In [ ]:
df.fillna(value='FILL VALUE')

In [ ]:
df.fillna(value=0)['A'].mean() #primero rellena un 0 y despues hace media (1+2+0)/3 que es 1

In [ ]:
df['A'].fillna(value=df['A'].mean())
# Los NaN los quita y pone la media de la columna (de los valores válidos)

---
## GroupBy

El método `groupby` permite agrupar datos por filas o columnas y utilizar funciones de agregación.

In [ ]:
data = {'Compañia':['GOOGLE','GOOGLE','MICROSOFT','MICROSOFT','FACEBOOK','FACEBOOK'],
       'Persona':['Juan','Miguel','Maria','Vanesa','Carlos','Sara'],
       'Sueldo':[200,120,340,124,243,350]}

df = pd.DataFrame(data)

df

    Compañia Persona  Sueldo
0     GOOGLE    Juan     200
1     GOOGLE  Miguel     120
2  MICROSOFT   Maria     340
3  MICROSOFT  Vanesa     124
4   FACEBOOK  Carlos     243
5   FACEBOOK    Sara     350

Ahora podemos usar el método `groupby` para agrupar filas a partir del nombre de la columna. Por ejemplo, podemos agrupar por *Compañia*. Esto creará un objeto DataFrameGroupBy:

In [ ]:
df.groupby('Compañia')

KeyError: 'Compañia'

Si guardamos el objeto en una variable, podemos llamar a diversos métodos de agregación y ver sus resultados:

In [ ]:
by_comp = df.groupby("Compañia")
#Media
by_comp.mean()

TypeError: dtype 'str' does not support operation 'mean'

In [ ]:
#Desviación estándar
by_comp.std()

In [ ]:
#Mínimo
by_comp.min()

In [ ]:
#Máximo
by_comp.max()

In [ ]:
#Contar
by_comp.count()

También se puede sacar diversos valores estadísticos:

In [ ]:
#Estadísticas
by_comp.describe()

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 1**: Consulta la ayuda del método `describe` para que muestre los percentiles cada 10%.

NOTA: para consultar la ayuda puedes utilizar `by_comp.describe?`

In [ ]:
# Solución Ejercicio 1
# Inserta en esta celda, a continuación, el código Python pedido
by_comp.describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

          Sueldo                                                               \
           count   mean         std    min    10%    20%    30%    40%    50%
Compañia
FACEBOOK     2.0  296.5   75.660426  243.0  253.7  264.4  275.1  285.8  296.5
GOOGLE       2.0  160.0   56.568542  120.0  128.0  136.0  144.0  152.0  160.0
MICROSOFT    2.0  232.0  152.735065  124.0  145.6  167.2  188.8  210.4  232.0


             60%    70%    80%    90%    max
Compañia
FACEBOOK   307.2  317.9  328.6  339.3  350.0
GOOGLE     168.0  176.0  184.0  192.0  200.0
MICROSOFT  253.6  275.2  296.8  318.4  340.0

In [ ]:
by_comp.describe?
by_comp.describe(percentiles=[0.1])

          Sueldo
           count   mean         std    min    10%    max
Compañia
FACEBOOK     2.0  296.5   75.660426  243.0  253.7  350.0
GOOGLE       2.0  160.0   56.568542  120.0  128.0  200.0
MICROSOFT    2.0  232.0  152.735065  124.0  145.6  340.0

Signature: by_comp.describe(percentiles=None, include=None, exclude=None) -> 'NDFrameT'
Docstring:
Generate descriptive statistics.

Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.

Analyzes both numeric and object series, as well
as ``DataFrame`` column sets of mixed data types. The output
will vary depending on what is provided. Refer to the notes
below for more detail.

Parameters
----------
percentiles : list-like of numbers, optional
    The percentiles to include in the output. All should
    fall between 0 and 1. The default, ``None``, will automatically
    return the 25th, 50th, and 75th percentiles.
include : 'all', list-like of dtypes or None (default), optional
    A white list of data types to include in the result. Ignored
    for ``Series``. Here are the options:

    - 'all' : All columns of the input will be included in the output.
    - A list-like of dtypes : Limits the results to the
      provided data types.
      To limit the result to numeric types submit
      ``numpy.number``. To limit it instead to object columns submit
      the ``numpy.object`` data type. Strings
      can also be used in the style of
      ``select_dtypes`` (e.g. ``df.describe(include=['O'])``). To
      select pandas categorical columns, use ``'category'``
    - None (default) : The result will include all numeric columns.
exclude : list-like of dtypes or None (default), optional,
    A black list of data types to omit from the result. Ignored
    for ``Series``. Here are the options:

    - A list-like of dtypes : Excludes the provided data types
      from the result. To exclude numeric types submit
      ``numpy.number``. To exclude object columns submit the data
      type ``numpy.object``. Strings can also be used in the style of
      ``select_dtypes`` (e.g. ``df.describe(exclude=['O'])``). To
      exclude pandas categorical columns, use ``'category'``
    - None (default) : The result will exclude nothing.

Returns
-------
Series or DataFrame
    Summary statistics of the Series or Dataframe provided.

See Also
--------
DataFrame.count: Count number of non-NA/null observations.
DataFrame.max: Maximum of the values in the object.
DataFrame.min: Minimum of the values in the object.
DataFrame.mean: Mean of the values.
DataFrame.std: Standard deviation of the observations.
DataFrame.select_dtypes: Subset of a DataFrame including/excluding
    columns based on their dtype.

Notes
-----
For numeric data, the result's index will include ``count``,
``mean``, ``std``, ``min``, ``max`` as well as lower, ``50`` and
upper percentiles. By default the lower percentile is ``25`` and the
upper percentile is ``75``. The ``50`` percentile is the
same as the median.

For object data (e.g. strings), the result's index
will include ``count``, ``unique``, ``top``, and ``freq``. The ``top``
is the most common value. The ``freq`` is the most common value's
frequency.

If multiple object values have the highest count, then the
``count`` and ``top`` results will be arbitrarily chosen from
among those with the highest count.

For mixed data types provided via a ``DataFrame``, the default is to
return only an analysis of numeric columns. If the DataFrame consists
only of object and categorical data without any numeric columns, the
default is to return an analysis of both the object and categorical
columns. If ``include='all'`` is provided as an option, the result
will include a union of attributes of each type.

The `include` and `exclude` parameters can be used to limit
which columns in a ``DataFrame`` are analyzed for the output.
The parameters are ignored when analyzing a ``Series``.

Examples
--------
Describing a numeric ``Series``.

>>> s = pd.Series([1, 2, 3])
>>> s.describe()
count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

Describing a categorical ``Series``.

>>> s = pd.Series(["a", "a", "b", "c"])
>>> s.describe()
count     4
unique    3
top       a
freq      2
dtype: object

Describing a timestamp ``Series``.

>>> s = pd.Series(
...     [
...         np.datetime64("2000-01-01"),
...         np.datetime64("2010-01-01"),
...         np.datetime64("2010-01-01"),
...     ]
... )
>>> s.describe()
count                      3
mean     2006-09-01 08:00:00
min      2000-01-01 00:00:00
25%      2004-12-31 12:00:00
50%      2010-01-01 00:00:00
75%      2010-01-01 00:00:00
max      2010-01-01 00:00:00
dtype: object

Describing a ``DataFrame``. By default only numeric fields
are returned.

>>> df = pd.DataFrame(
...     {
...         "categorical": pd.Categorical(["d", "e", "f"]),
...         "numeric": [1, 2, 3],
...         "object": ["a", "b", "c"],
...     }
... )
>>> df.describe()
       numeric
count      3.0
mean       2.0
std        1.0
min        1.0
25%        1.5
50%        2.0
75%        2.5
max        3.0

Describing all columns of a ``DataFrame`` regardless of data type.

>>> df.describe(include="all")  # doctest: +SKIP
       categorical  numeric object
count            3      3.0      3
unique           3      NaN      3
top              f      NaN      a
freq             1      NaN      1
mean           NaN      2.0    NaN
std            NaN      1.0    NaN
min            NaN      1.0    NaN
25%            NaN      1.5    NaN
50%            NaN      2.0    NaN
75%            NaN      2.5    NaN
max            NaN      3.0    NaN

Describing a column from a ``DataFrame`` by accessing it as
an attribute.

>>> df.numeric.describe()
count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
Name: numeric, dtype: float64

Including only numeric columns in a ``DataFrame`` description.

>>> df.describe(include=[np.number])
       numeric
count      3.0
mean       2.0
std        1.0
min        1.0
25%        1.5
50%        2.0
75%        2.5
max        3.0

Including only string columns in a ``DataFrame`` description.

>>> df.describe(include=[object])  # doctest: +SKIP
       object
count       3
unique      3
top         a
freq        1

Including only categorical columns from a ``DataFrame`` description.

>>> df.describe(include=["category"])
       categorical
count            3
unique           3
top              d
freq             1

Excluding numeric columns from a ``DataFrame`` description.

>>> df.describe(exclude=[np.number])  # doctest: +SKIP
       categorical object
count            3      3
unique           3      3
top              f      a
freq             1      1

Excluding object columns from a ``DataFrame`` description.

>>> df.describe(exclude=[object])  # doctest: +SKIP
       categorical  numeric
count            3      3.0
unique           3      NaN
top              f      NaN
freq             1      NaN
mean           NaN      2.0
std            NaN      1.0
min            NaN      1.0
25%            NaN      1.5
50%            NaN      2.0
75%            NaN      2.5
max            NaN      3.0
File:      c:\users\benro\appdata\local\programs\python\python313\lib\site-packages\pandas\core\groupby\groupby.py
Type:      method

Si no puedes ver bien los datos, puede mostrarlos en sentido contrario:

In [ ]:
by_comp.describe().transpose()

El método `describe` devuelve un DataFrame, por lo que se puede filtrar los datos obtenidos por etiqueta.

In [ ]:
by_comp.describe().transpose()['GOOGLE']

---
## Mezcla, unión y concatenación

Existen 3 formas de combinar DataFrames: mezcla, unión y concatenación. A continuación veremos la diferencia entre elos con varios ejemplos.

### DataFrames de ejemplo

Primero crearemos varios DataFrames de ejemplo para realizar la combinación.

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

### Concatenación

La concatenación básicamente une los DataFrames. Hay que tener en cuenta que las dimensiones deben coindicir en el eje en que se concatena. Para la concatenación utilizamos `pd.concat` pasándole una lista con los DataFrames que queremos concatenar:

In [ ]:
pd.concat([df1,df2,df3])

In [ ]:
#Concatenar por columnas
pd.concat([df1,df2,df3],axis=1)

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[0, 1, 2, 3]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[0, 1, 2, 3])
pd.concat([df1,df2,df3],axis=1)

### Mezcla

La función `merge` nos permite mezclar DataFrames utilizando una columna como clave de mezcla Dicha mezcla la realiza de forma similar a como lo hace el `JOIN` de `SQL`. Vamos a crear un par de DataFrames de ejemplo para ilustrar la mezcla:

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'keyA': ['A0', 'A1', 'A2', 'A3'],
                     'keyB': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K2', 'K1', 'K3'],
                          'keyC': ['C0', 'C1', 'C2', 'C3'],
                          'keyD': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
left

  key keyA keyB
0  K0   A0   B0
1  K1   A1   B1
2  K2   A2   B2
3  K3   A3   B3

In [ ]:
right

  key keyC keyD
0  K0   C0   D0
1  K2   C1   D1
2  K1   C2   D2
3  K3   C3   D3

In [ ]:
pd.merge(left,right,how='inner',on='key')

  key keyA keyB keyC keyD
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C2   D2
2  K2   A2   B2   C1   D1
3  K3   A3   B3   C3   D3

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'keyA': ['A0', 'A1', 'A2', 'A3'],
                     'keyB': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K4', 'K1', 'K3'],
                          'keyC': ['C0', 'C1', 'C2', 'C3'],
                          'keyD': ['D0', 'D1', 'D2', 'D3']})  
pd.merge(left,right,how='inner',on='key')

  key keyA keyB keyC keyD
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C2   D2
2  K3   A3   B3   C3   D3

In [ ]:
pd.merge(left,right,how='outer',on='key')

  key keyA keyB keyC keyD
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C2   D2
2  K2   A2   B2  NaN  NaN
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C1   D1

In [ ]:
pd.merge(left,right,how='left',on='key')

  key keyA keyB keyC keyD
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C2   D2
2  K2   A2   B2  NaN  NaN
3  K3   A3   B3   C3   D3

In [ ]:
pd.merge(left,right,how='right',on='key')

  key keyA keyB keyC keyD
0  K0   A0   B0   C0   D0
1  K4  NaN  NaN   C1   D1
2  K1   A1   B1   C2   D2
3  K3   A3   B3   C3   D3

Otro ejemplo mas complejo sería:

In [ ]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                         'C': ['C0', 'C1', 'C2', 'C3'],
                         'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
#Mezclar sólo claves comunes
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
#Mezclar utilizando todas las claves
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [ ]:
#Mezclar utilizado claves del segundo DataFrame
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
#Mezclar utilizando claves del primer DataFrame
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 2**: Consulta la ayuda del método `merge` para que el resultado obtenido contenga una columna que indique de que DataFrame proviene la fila en la mezcla.

In [285]:
# Solución Ejercicio 2
# Inserta en esta celda, a continuación, el código Python pedido
pd.merge(left, right, how='outer', on='key', indicator=True)

  key keyA keyB keyC keyD _merge
0  K0   A0   B0   C0   D0   both
1  K1   A1   B1   C2   D2   both
2  K2   A2   B2   C1   D1   both
3  K3   A3   B3   C3   D3   both

In [383]:
pd.merge

<function pandas.merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | lib.NoDefault' = <no_default>, indicator: 'str | bool' = False, validate: 'str | None' = None) -> 'DataFrame'>

In [384]:
pd.merge_ordered

<function pandas.merge_ordered(left: 'DataFrame | Series', right: 'DataFrame | Series', on: 'IndexLabel | None' = None, left_on: 'IndexLabel | None' = None, right_on: 'IndexLabel | None' = None, left_by=None, right_by=None, fill_method: 'str | None' = None, suffixes: 'Suffixes' = ('_x', '_y'), how: 'JoinHow' = 'outer') -> 'DataFrame'>

### Unión

El método `join` realiza una operación similar a la mezcla, solo que utiliza los propios índices del DataFrame, en lugar de las columnas indicadas.

In [358]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                     index=['K0', 'K2', 'K3'])

left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [359]:
#Utiliza la unión de los índices de ambos DataFrames
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 3**: Realiza la unión de ambos DataFrames de forma que el resultado sea un DataFrame que sólo contenga los índices que estén en ambos DataFrames.

In [385]:
# Solución Ejercicio 3
# Inserta en esta celda, a continuación, el código Python pedido
left.join(right, how='inner')

     A   B   C   D
K0  A0  B0  C0  D0
K2  A2  B2  C2  D2

---
## Operaciones

Existen multitud de operaciones en Pandas que pueden ser de utilidad, pero que no pueden clasificar en ninguna categoría. Veamos algunas de ellas.

### Cabecera

Si el DataFrame contiene una gran cantidad de filas podemos visualizar sólo la cabecera (las 5 primeras filas) con el método `head`.

In [361]:
df = pd.DataFrame({'col1':[1,2,3,4,5,6],
                   'col2':[444,555,666,444,555,555],
                   'col3':['abc','def','ghi','jkl','mno','xyz']})
df.head(4)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

### Valores únicos

In [362]:
#Listado de valores únicos
df['col2'].unique()

array([444, 555, 666])

In [363]:
#Cantidad de valores únicos
df['col2'].nunique()

3

In [364]:
#Listado y cantidad de valores únicos
df['col2'].value_counts()

col2
555    3
444    2
666    1
Name: count, dtype: int64

### Aplicar una función a cada valor

In [365]:
def times2(x):
    return x*2

df['col1'].apply(times2)

0     2
1     4
2     6
3     8
4    10
5    12
Name: col1, dtype: int64

In [366]:
df['col2'].apply(np.sqrt)

0    21.071308
1    23.558438
2    25.806976
3    21.071308
4    23.558438
5    23.558438
Name: col2, dtype: float64

In [367]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
4    3
5    3
Name: col3, dtype: int64

### Eliminar permanentemente una columna

In [368]:
del df['col1'] # borra en el objeto original

df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  jkl
4   555  mno
5   555  xyz

In [369]:
df.drop(4,axis=0,inplace=True)
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  jkl
5   555  xyz

### Conocer los nombres de columnas e índices

In [370]:
df.columns

Index(['col2', 'col3'], dtype='str')

In [371]:
df.index

Index([0, 1, 2, 3, 5], dtype='int64')

### Ordenar un DataFrame

In [372]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  jkl
5   555  xyz

In [373]:
df.sort_values(by='col2') #por defecto no modifica el DataFrame (inplace=False)

   col2 col3
0   444  abc
3   444  jkl
1   555  def
5   555  xyz
2   666  ghi

### Encontrar valores nulos

In [374]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False
5  False  False

### Resumen de datos.

Un resumen de datos es similar a las tablas dinámicas de Excel o las *tablas pivote* de OpenOffice.

In [375]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
        'B':['one','one','two','two','one','one'],
        'C':['x','y','x','y','x','y'],
        'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [376]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [377]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'],aggfunc=[np.mean,np.max])

        mean       max
C          x    y    x    y
A   B
bar one  4.0  1.0  4.0  1.0
    two  NaN  5.0  NaN  5.0
foo one  1.0  3.0  1.0  3.0
    two  2.0  NaN  2.0  NaN

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 4**: Crea un DataFrame con 3 columnas: alumno, actividad, nota. A continuación obtén una tabla resumen con la nota media de cada alumno.

In [3]:
# Solución Ejercicio 4
# Inserta en esta celda, a continuación, el código Python pedido

# Crear DataFrame con 3 columnas: alumno, actividad, nota
data = {
    'alumno': ['Juan', 'María', 'Pedro', 'Juan', 'María', 'Pedro', 'Juan', 'María'],
    'actividad': ['Examen1', 'Examen1', 'Examen1', 'Examen2', 'Examen2', 'Examen2', 'Proyecto', 'Proyecto'],
    'nota': [8.5, 9.0, 7.5, 7.0, 8.5, 9.0, 9.5, 8.0]
}

df_ejercicio4 = pd.DataFrame(data)
print("DataFrame original:")
print(df_ejercicio4)
print("\n" + "="*50 + "\n")

# Obtener tabla resumen con la nota media de cada alumno
resumen_notas = df_ejercicio4.groupby('alumno')['nota'].mean()
print("Tabla resumen - Nota media por alumno:")
print(resumen_notas)

DataFrame original:
  alumno actividad  nota
0   Juan   Examen1   8.5
1  María   Examen1   9.0
2  Pedro   Examen1   7.5
3   Juan   Examen2   7.0
4  María   Examen2   8.5
5  Pedro   Examen2   9.0
6   Juan  Proyecto   9.5
7  María  Proyecto   8.0

==================================================

Tabla resumen - Nota media por alumno:
alumno
Juan     8.333333
María    8.500000
Pedro    8.250000
Name: nota, dtype: float64

---
## Entrada y salida de datos.

Pandas puede leer y escribir una gran variedad de tipos de ficheros. Para ello se utilizan métodos del tipo `pd.read_...` para leer o `df.to_...` para escribir o generar la salida. Veamos algunos ejemplos de los tipos mas comunes.

### CSV

In [5]:
#Leer un fichero CSV
df = pd.read_csv('datos/ejemplo.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [380]:
#Escribir un fichero CSV
df.to_csv('datos/ejemplo2.csv',index=False)

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 5**: Busca en la ayuda de `df.to_csv` y guarda el DataFrame en un fichero CSV pero separando los valores con tabuladores.

In [6]:
# Solución Ejercicio 5
# Inserta en esta celda, a continuación, el código Python pedido

# Guardar el DataFrame en un fichero CSV separando los valores con tabuladores
df.to_csv('datos/ejemplo_tabuladores.csv', index=False, sep='\t')

### MS-Excel

Pandas puede leer y escribir ficheros de Excel, teniendo en cuenta que sólo puede importar los datos (sin fórmulas o imágenes). Si la hoja de Excel tiene imágenes o macros el método `read_excel` podría no funcionar.

In [382]:
#Leer una hoja de Excel
pd.read_excel('datos/Ejemplo_Excel.xlsx',sheet_name='Hoja1')

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [ ]:
#Escribir en una hoja de Excel
df.to_excel('datos/Ejemplo_Excel2.xlsx',sheet_name='Hoja2')

### HTML

Para poder leer tablas existentes en páginas HTML o escribir tablas HTML es recomendable tener instaladas las siguientes librerías: htmllib5, lxml y BeautifulSoup4.

Si no las tenías instaladas y lo acabas de hacer deberías reiniciar Jupyter Notebook.

Pandas puede leer tablas de una página web y devolver una lista de DataFrames con las tablas encontradas. Por ejemplo:

In [9]:
tabla='Politécnica'
df = pd.read_html('https://www.ujaen.es/estudios/oferta-academica/grados', match=tabla)

In [10]:
df[0]

,Oferta,Doble título internacional,Modalidad de enseñanza,Idiomas,Centro
0,Doble Grado en Ingeniería Civil y Grado en Ing...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
1,Doble Grado en Ingeniería Civil y Grado en Ing...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
2,Doble Grado en Ingeniería de la Energía y Grad...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
3,Doble Grado en Ingeniería de Recursos Energéti...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
4,Doble Grado en Ingeniería de Tecnologías de Te...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
5,Doble Grado en Ingeniería Eléctrica y Grado en...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
6,Doble Grado en Ingeniería Eléctrica y Grado en...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
7,Doble Grado en Ingeniería Eléctrica y Grado en...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
8,Doble Grado en Ingeniería Electrónica Industri...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
9,Doble Grado en Ingeniería Mecánica y Grado en ...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
10,Grado en Ingeniería Civil (EPS Linares) (RD 13...,Sí,Presencial,Castellano,Escuela Politécnica Superior de Linares
11,Grado en Ingeniería Civil (EPS Linares) (RD. 8...,Sí,Presencial,Castellano,Escuela Politécnica Superior de Linares
12,Grado en Ingeniería de la Energía (EPS Linares),No,Presencial,Castellano,Escuela Politécnica Superior de Linares
13,Grado en Ingeniería de Organización Industrial...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
14,Grado en Ingeniería de Recursos Energéticos (E...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
15,Grado en Ingeniería de Tecnologías de Telecomu...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
16,Grado en Ingeniería de Tecnologías Mineras (EP...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
17,Grado en Ingeniería de Tecnologías Mineras (EP...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
18,Grado en Ingeniería Eléctrica (EPS Jaén),No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
19,Grado en Ingeniería Eléctrica (EPS Linares),No,Presencial,Castellano,Escuela Politécnica Superior de Linares
20,Grado en Ingeniería Electrónica Industrial (EP...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
21,Grado en Ingeniería Geomática y Topográfica (E...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
22,Grado en Ingeniería Geomática y Topográfica (E...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
23,Grado en Ingeniería Informática (EPS Jaén),No,Presencial,Castellano,Escuela Politécnica Superior de Jaén
24,Grado en Ingeniería Mecánica (EPS Jaén),Sí,Presencial,Castellano,Escuela Politécnica Superior de Jaén
25,Grado en Ingeniería Mecánica (EPS Linares),Sí,Presencial,Castellano,Escuela Politécnica Superior de Linares
26,Grado en Ingeniería Química Industrial (EPS Li...,No,Presencial,Castellano,Escuela Politécnica Superior de Linares
27,Grado en Ingeniería Telemática (EPS Linares),No,Presencial,Castellano,Escuela Politécnica Superior de Linares
28,Grado en Inteligencia Artificial y Ciberseguri...,No,Presencial,Castellano,Escuela Politécnica Superior de Jaén

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 6**: Busca las ordenes necesarias para escribir un DataFrame en los siguientes formatos: HTML, JSON, $LaTeX$. Después úsalas en un ejemplo insertando la última tabla obtenida en los tres formatos en tres ficheros distintos y después muéstralos por pantalla.

In [11]:
# Solución Ejercicio 6
# Inserta en esta celda, a continuación, el código Python pedido

# Buscar las órdenes para escribir en HTML, JSON y LaTeX
# Para consultar la ayuda de cada método, usar:
# df[0].to_html?
# df[0].to_json?
# df[0].to_latex?

# Guardar la última tabla obtenida (df[0]) en los tres formatos
# HTML
df[0].to_html('datos/ejemplo_tabla.html', index=False)
print("=== Archivo HTML guardado: datos/ejemplo_tabla.html ===")

# JSON
df[0].to_json('datos/ejemplo_tabla.json', orient='records', indent=2)
print("=== Archivo JSON guardado: datos/ejemplo_tabla.json ===")

# LaTeX
df[0].to_latex('datos/ejemplo_tabla.tex', index=False)
print("=== Archivo LaTeX guardado: datos/ejemplo_tabla.tex ===")

# Mostrar los archivos por pantalla
print("\n" + "="*60)
print("CONTENIDO DEL ARCHIVO HTML:")
print("="*60)
with open('datos/ejemplo_tabla.html', 'r', encoding='utf-8') as f:
    print(f.read())

print("\n" + "="*60)
print("CONTENIDO DEL ARCHIVO JSON:")
print("="*60)
with open('datos/ejemplo_tabla.json', 'r', encoding='utf-8') as f:
    print(f.read())

print("\n" + "="*60)
print("CONTENIDO DEL ARCHIVO LaTeX:")
print("="*60)
with open('datos/ejemplo_tabla.tex', 'r', encoding='utf-8') as f:
    print(f.read())

=== Archivo HTML guardado: datos/ejemplo_tabla.html ===
=== Archivo JSON guardado: datos/ejemplo_tabla.json ===
=== Archivo LaTeX guardado: datos/ejemplo_tabla.tex ===

============================================================
CONTENIDO DEL ARCHIVO HTML:
============================================================
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Oferta</th>
      <th>Doble título internacional</th>
      <th>Modalidad de enseñanza</th>
      <th>Idiomas</th>
      <th>Centro</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Doble Grado en Ingeniería Civil y Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 1393/2007)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Civil y Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 822/2021)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería de la Energía y Grado en Ingeniería de Tecnologías Mineras (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería de Recursos Energéticos y Grado en Ingeniería Química Industrial (EPS Linares). Plan en Extinción</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería de Tecnologías de Telecomunicación y Grado en Ingeniería Telemática (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Electrónica Industrial (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Mecánica (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Mecánica (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Electrónica Industrial y Grado en Ingeniería Mecánica (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Doble Grado en Ingeniería Mecánica y Grado en Ingeniería en Organización Industrial (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Civil (EPS Linares) (RD 1393/2007)</td>
      <td>Sí</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Civil (EPS Linares) (RD. 822/2021)</td>
      <td>Sí</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de la Energía (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de Organización Industrial (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de Recursos Energéticos (EPS Linares). Plan en Extinción</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de Tecnologías de Telecomunicación (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 1393/2007)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD. 822/2021)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Eléctrica (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Eléctrica (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Electrónica Industrial (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Geomática y Topográfica (EPS Jaén - en extinción)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Geomática y Topográfica (EPS Jaén - plan 2025)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Informática (EPS Jaén)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Mecánica (EPS Jaén)</td>
      <td>Sí</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Mecánica (EPS Linares)</td>
      <td>Sí</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Química Industrial (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Ingeniería Telemática (EPS Linares)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Linares</td>
    </tr>
    <tr>
      <td>Grado en Inteligencia Artificial y Ciberseguridad (EPS Jaén - Interuniversitario UAL)</td>
      <td>No</td>
      <td>Presencial</td>
      <td>Castellano</td>
      <td>Escuela Politécnica Superior de Jaén</td>
    </tr>
  </tbody>
</table>

============================================================
CONTENIDO DEL ARCHIVO JSON:
============================================================
[
  {
    "Oferta":"Doble Grado en Ingenier\u00eda Civil y Grado en Ingenier\u00eda de Tecnolog\u00edas Mineras (EPS Linares) (RD 1393\/2007)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda Civil y Grado en Ingenier\u00eda de Tecnolog\u00edas Mineras (EPS Linares) (RD 822\/2021)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda de la Energ\u00eda y Grado en Ingenier\u00eda de Tecnolog\u00edas Mineras (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda de Recursos Energ\u00e9ticos y Grado en Ingenier\u00eda Qu\u00edmica Industrial (EPS Linares). Plan en Extinci\u00f3n",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda de Tecnolog\u00edas de Telecomunicaci\u00f3n y Grado en Ingenier\u00eda Telem\u00e1tica (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda El\u00e9ctrica y Grado en Ingenier\u00eda Electr\u00f3nica Industrial (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda El\u00e9ctrica y Grado en Ingenier\u00eda Mec\u00e1nica (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda El\u00e9ctrica y Grado en Ingenier\u00eda Mec\u00e1nica (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda Electr\u00f3nica Industrial y Grado en Ingenier\u00eda Mec\u00e1nica (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Doble Grado en Ingenier\u00eda Mec\u00e1nica y Grado en Ingenier\u00eda en Organizaci\u00f3n Industrial (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Civil (EPS Linares) (RD 1393\/2007)",
    "Doble t\u00edtulo internacional":"S\u00ed",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Civil (EPS Linares) (RD. 822\/2021)",
    "Doble t\u00edtulo internacional":"S\u00ed",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de la Energ\u00eda (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de Organizaci\u00f3n Industrial (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de Recursos Energ\u00e9ticos (EPS Linares). Plan en Extinci\u00f3n",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de Tecnolog\u00edas de Telecomunicaci\u00f3n (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de Tecnolog\u00edas Mineras (EPS Linares) (RD 1393\/2007)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda de Tecnolog\u00edas Mineras (EPS Linares) (RD. 822\/2021)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda El\u00e9ctrica (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda El\u00e9ctrica (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Electr\u00f3nica Industrial (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Geom\u00e1tica y Topogr\u00e1fica (EPS Ja\u00e9n - en extinci\u00f3n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Geom\u00e1tica y Topogr\u00e1fica (EPS Ja\u00e9n - plan 2025)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Inform\u00e1tica (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Mec\u00e1nica (EPS Ja\u00e9n)",
    "Doble t\u00edtulo internacional":"S\u00ed",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Mec\u00e1nica (EPS Linares)",
    "Doble t\u00edtulo internacional":"S\u00ed",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Qu\u00edmica Industrial (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Ingenier\u00eda Telem\u00e1tica (EPS Linares)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Linares"
  },
  {
    "Oferta":"Grado en Inteligencia Artificial y Ciberseguridad (EPS Ja\u00e9n - Interuniversitario UAL)",
    "Doble t\u00edtulo internacional":"No",
    "Modalidad de ense\u00f1anza":"Presencial",
    "Idiomas":"Castellano",
    "Centro":"Escuela Polit\u00e9cnica Superior de Ja\u00e9n"
  }
]

============================================================
CONTENIDO DEL ARCHIVO LaTeX:
============================================================
\begin{tabular}{lllll}
\toprule
Oferta & Doble título internacional & Modalidad de enseñanza & Idiomas & Centro \\
\midrule
Doble Grado en Ingeniería Civil y Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 1393/2007) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería Civil y Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 822/2021) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería de la Energía y Grado en Ingeniería de Tecnologías Mineras (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería de Recursos Energéticos y Grado en Ingeniería Química Industrial (EPS Linares). Plan en Extinción & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería de Tecnologías de Telecomunicación y Grado en Ingeniería Telemática (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Electrónica Industrial (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Mecánica (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Doble Grado en Ingeniería Eléctrica y Grado en Ingeniería Mecánica (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Doble Grado en Ingeniería Electrónica Industrial y Grado en Ingeniería Mecánica (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Doble Grado en Ingeniería Mecánica y Grado en Ingeniería en Organización Industrial (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Civil (EPS Linares) (RD 1393/2007) & Sí & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería Civil (EPS Linares) (RD. 822/2021) & Sí & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería de la Energía (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería de Organización Industrial (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería de Recursos Energéticos (EPS Linares). Plan en Extinción & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería de Tecnologías de Telecomunicación (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD 1393/2007) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería de Tecnologías Mineras (EPS Linares) (RD. 822/2021) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería Eléctrica (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Eléctrica (EPS Linares) & No & Presencial & Castellano & Escuela Politécnica Superior de Linares \\
Grado en Ingeniería Electrónica Industrial (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Geomática y Topográfica (EPS Jaén - en extinción) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Geomática y Topográfica (EPS Jaén - plan 2025) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Informática (EPS Jaén) & No & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\
Grado en Ingeniería Mecánica (EPS Jaén) & Sí & Presencial & Castellano & Escuela Politécnica Superior de Jaén \\

## Referencias.

* [Python Pandas Cheat Sheet](http://nbviewer.jupyter.org/github/pybokeh/ipython_notebooks/blob/master/pandas/PandasCheatSheet.ipynb)
* [Modern Pandas](http://tomaugspurger.github.io/modern-1.html)